# -*- coding: utf-8 -*-
"""calculadora.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QW9mTnyOrgsGTiiJ-Oi_NVQUrF8p1DbG
"""

nome = input("Qual o seu nome? ")
print("Olá,", nome, "seja bem-vindo(a) à calculadora!")

while True:
    primeiro_numero = int(input("Digite o primeiro número inteiro: "))
    segundo_numero = int(input("Digite o segundo número inteiro: "))
    sinal = input("Agora escolha um sinal para calcularmos os dois números, pode ser +, -, * ou /: ")

    if sinal == "+":
        print("O resultado é", primeiro_numero + segundo_numero)
    elif sinal == "-":
        print("O resultado é", primeiro_numero - segundo_numero)
    elif sinal == "*":
        print("O resultado é", primeiro_numero * segundo_numero)
    elif sinal == "/":
        print("O resultado é", primeiro_numero / segundo_numero)
    else:
        print("Sinal inválido!")

    confirmacao = input("Deseja calcular novamente? Digite sim ou não: ")
    if confirmacao.lower() in ["não", "nao"]:
        print("Obrigado por usar a calculadora!")
        break